// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import openNextWorker from "./.open-next/worker.js";

// ─── Cache Configuration ──────────────────────────────────────────────────────

const LISTING_PATHNAME = "/products";
const LISTING_EDGE_TTL_SECONDS = 300;
const LISTING_CACHE_CONTROL = `public, max-age=0, s-maxage=${LISTING_EDGE_TTL_SECONDS}, stale-while-revalidate=60`;

/**
 *  Value to immediately invalidate all cached listing variants
 * across every edge location on the next deploy — no manual purge required.
 */
const LISTING_CACHE_VERSION = "v2";

// ─── Types ────────────────────────────────────────────────────────────────────

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getDefaultCache() {
  return (caches as CacheStorage & { default: Cache }).default;
}

async function sha256Hex(value: string) {
  const data = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest("SHA-256", data);

  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Derives a per-user cache variant from the session cookie.
 * The cookie value is URL-decoded before hashing so that encoded and
 * unencoded representations of the same identity resolve to the same key.
 * Falls back to "guest" for unauthenticated requests.
 */
async function getListingCacheVariant(request: Request) {
  const cookieHeader = request.headers.get("cookie") ?? "";
  const sessionUser = cookieHeader.match(/(?:^|;\s*)sessionUser=([^;]*)/)?.[1];

  if (sessionUser) {
    try {
      return sha256Hex(decodeURIComponent(sessionUser));
    } catch {
      return sha256Hex(sessionUser);
    }
  }

  return "guest";
}

/**
 * Builds a normalised cache key that encodes the cache version, the
 * per-user variant, and a fixed Accept header so that RSC / prefetch
 * requests never collide with full document requests.
 */
async function createListingCacheKey(request: Request) {
  const url = new URL(request.url);
  const variant = await getListingCacheVariant(request);

  url.searchParams.set("__cache_version", LISTING_CACHE_VERSION);
  url.searchParams.set("__edge_variant", variant);

  return new Request(url.toString(), {
    method: "GET",
    headers: {
      Accept: request.headers.get("accept") ?? "text/html",
    },
  });
}

function isListingRequest(request: Request) {
  const url = new URL(request.url);
  const accept = request.headers.get("accept") ?? "";
  const secFetchDest = request.headers.get("sec-fetch-dest");

  return (
    request.method === "GET" &&
    url.pathname === LISTING_PATHNAME &&
    accept.includes("text/html") &&
    !request.headers.has("rsc") &&
    !request.headers.has("next-router-prefetch") &&
    !request.headers.has("next-url") &&          // RSC navigation requests
    !url.searchParams.has("_rsc") &&              // RSC param used in some Next versions
    (secFetchDest === null || secFetchDest === "document")
  );
}

function isCacheableListingResponse(response: Response) {
  const contentType = response.headers.get("content-type") ?? "";
  const vary = response.headers.get("vary") ?? "";

  return (
    response.ok &&
    contentType.includes("text/html") &&
    !response.headers.has("set-cookie") &&
    !vary.includes("RSC")                         // Next sets Vary: RSC on partial responses
  );
}
/**
 * Derives a clean header set from the origin response.
 * content-length and content-encoding are stripped because the body is
 * always fully decoded via .text() before being wrapped in a new Response.
 */
function createListingHeaders(
  response: Response,
  status: "HIT" | "MISS",
  includeCacheControl = true,
) {
  const headers = new Headers(response.headers);
  headers.set("x-cache-status", status);
  headers.delete("content-length");
  headers.delete("content-encoding");

  if (includeCacheControl) {
    headers.set("Cache-Control", LISTING_CACHE_CONTROL);
  }

  return headers;
}

async function normalizeListingResponse(
  response: Response,
  status: "HIT" | "MISS",
) {
  const html = await response.text();
  const headers = createListingHeaders(response, status);

  return new Response(html, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

// ─── Worker ───────────────────────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: unknown, ctx: WorkerExecutionContext) {
    if (!isListingRequest(request)) {
      return openNextWorker.fetch(request, env, ctx);
    }

    const cacheKey = await createListingCacheKey(request);
    const edgeCache = getDefaultCache();
    const cachedResponse = await edgeCache.match(cacheKey);

    if (cachedResponse) {
      return normalizeListingResponse(cachedResponse, "HIT");
    }

    const originResponse = await openNextWorker.fetch(request, env, ctx);

    if (!isCacheableListingResponse(originResponse)) {
      const headers = createListingHeaders(originResponse, "MISS", false);

      return new Response(originResponse.body, {
        status: originResponse.status,
        statusText: originResponse.statusText,
        headers,
      });
    }

    // Store the response with HIT status so cache reads don't need to
    // overwrite the header on every request. The caller receives its own
    // MISS-labelled response built from a clone of the same body.
    const responseToCache = await normalizeListingResponse(originResponse, "HIT");

    const responseToReturn = new Response(responseToCache.clone().body, {
      status: responseToCache.status,
      statusText: responseToCache.statusText,
      headers: createListingHeaders(responseToCache, "MISS"),
    });

    ctx.waitUntil(edgeCache.put(cacheKey, responseToCache.clone()));

    return responseToReturn;
  },
};